# Generated by Django 4.0.4 on 2022-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Code"),
        ),
    ]
