# Generated by Django 4.0.4 on 2022-04-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
